CREATE DATABASE pulpit_parking_system;
USE pulpit_parking_system;
CREATE TABLE City (
    city_id INT PRIMARY KEY,
    city_name VARCHAR(100) NOT NULL,
    state VARCHAR(100) NOT NULL
);
CREATE TABLE Parking_Location (
    location_id INT PRIMARY KEY,
    city_id INT NOT NULL,
    location_name VARCHAR(150) NOT NULL,
    address VARCHAR(255),
    total_capacity INT NOT NULL,
    FOREIGN KEY (city_id) REFERENCES City(city_id)
);
CREATE TABLE Parking_Zone (
    zone_id INT PRIMARY KEY,
    location_id INT NOT NULL,
    zone_name VARCHAR(50),
    floor_level INT,
    FOREIGN KEY (location_id) REFERENCES Parking_Location(location_id)
);
CREATE TABLE Slot_Type (
    slot_type_id INT PRIMARY KEY,
    slot_type_name VARCHAR(50) NOT NULL,
    base_hourly_rate DECIMAL(10,2) NOT NULL
);
CREATE TABLE Parking_Slot (
    slot_id INT PRIMARY KEY,
    zone_id INT NOT NULL,
    slot_type_id INT NOT NULL,
    slot_number VARCHAR(20) NOT NULL,
    is_active BOOLEAN DEFAULT TRUE,
    FOREIGN KEY (zone_id) REFERENCES Parking_Zone(zone_id),
    FOREIGN KEY (slot_type_id) REFERENCES Slot_Type(slot_type_id)
);
CREATE TABLE User (
    user_id INT PRIMARY KEY,
    full_name VARCHAR(150) NOT NULL,
    phone_number VARCHAR(15),
    email VARCHAR(150)
);
CREATE TABLE Vehicle (
    vehicle_id INT PRIMARY KEY,
    user_id INT NOT NULL,
    registration_number VARCHAR(20) NOT NULL,
    vehicle_type VARCHAR(50),
    FOREIGN KEY (user_id) REFERENCES User(user_id)
);
CREATE TABLE Booking (
    booking_id INT PRIMARY KEY,
    user_id INT NOT NULL,
    vehicle_id INT NOT NULL,
    slot_id INT NOT NULL,
    booking_start_time DATETIME NOT NULL,
    booking_end_time DATETIME NOT NULL,
    booking_type VARCHAR(30),
    booking_status VARCHAR(30),
    FOREIGN KEY (user_id) REFERENCES User(user_id),
    FOREIGN KEY (vehicle_id) REFERENCES Vehicle(vehicle_id),
    FOREIGN KEY (slot_id) REFERENCES Parking_Slot(slot_id)
);
CREATE TABLE Payment_Method (
    payment_method_id INT PRIMARY KEY,
    method_name VARCHAR(50) NOT NULL
);
CREATE TABLE Payment (
    payment_id INT PRIMARY KEY,
    booking_id INT NOT NULL,
    payment_method_id INT NOT NULL,
    amount_paid DECIMAL(10,2) NOT NULL,
    payment_time DATETIME,
    payment_status VARCHAR(30),
    FOREIGN KEY (booking_id) REFERENCES Booking(booking_id),
    FOREIGN KEY (payment_method_id) REFERENCES Payment_Method(payment_method_id)
);
CREATE TABLE Entry_Exit_Log (
    log_id INT PRIMARY KEY,
    booking_id INT NOT NULL,
    entry_time DATETIME,
    exit_time DATETIME,
    FOREIGN KEY (booking_id) REFERENCES Booking(booking_id)
);
CREATE TABLE Violation (
    violation_id INT PRIMARY KEY,
    booking_id INT NOT NULL,
    violation_type VARCHAR(100),
    penalty_amount DECIMAL(10,2),
    violation_time DATETIME,
    FOREIGN KEY (booking_id) REFERENCES Booking(booking_id)
);

##Queries 
SELECT 
    c.city_name,
    p.location_name,
    p.address
FROM City c
JOIN Parking_Location p
    ON c.city_id = p.city_id;
    
## Show all zones in each parking location   
SELECT
    p.location_name,
    z.zone_name,
    z.floor_level
FROM Parking_Location p
JOIN Parking_Zone z
    ON p.location_id = z.location_id;
    
    
##List all parking slots with slot type and rate
SELECT
    ps.slot_number,
    st.slot_type_name,
    st.base_hourly_rate
FROM Parking_Slot ps
JOIN Slot_Type st
    ON ps.slot_type_id = st.slot_type_id;

##Fetch all vehicles registered by users
SELECT
    u.full_name,
    v.registration_number,
    v.vehicle_type
FROM User u
JOIN Vehicle v
    ON u.user_id = v.user_id;

##Show booking details with user and slot information
SELECT
    b.booking_id,
    u.full_name,
    ps.slot_number,
    b.booking_start_time,
    b.booking_end_time,
    b.booking_status
FROM Booking b
JOIN User u
    ON b.user_id = u.user_id
JOIN Parking_Slot ps
    ON b.slot_id = ps.slot_id;

##Total revenue generated by each parking location
SELECT
    pl.location_name,
    SUM(p.amount_paid) AS total_revenue
FROM Payment p
JOIN Booking b
    ON p.booking_id = b.booking_id
JOIN Parking_Slot ps
    ON b.slot_id = ps.slot_id
JOIN Parking_Zone z
    ON ps.zone_id = z.zone_id
JOIN Parking_Location pl
    ON z.location_id = pl.location_id
GROUP BY pl.location_name;

##Total revenue generated city-wise
SELECT
    c.city_name,
    SUM(p.amount_paid) AS city_revenue
FROM Payment p
JOIN Booking b
    ON p.booking_id = b.booking_id
JOIN Parking_Slot ps
    ON b.slot_id = ps.slot_id
JOIN Parking_Zone z
    ON ps.zone_id = z.zone_id
JOIN Parking_Location pl
    ON z.location_id = pl.location_id
JOIN City c
    ON pl.city_id = c.city_id
GROUP BY c.city_name;

##Revenue generated by slot type (Regular, EV, Reserved)
SELECT
    st.slot_type_name,
    SUM(p.amount_paid) AS revenue_by_slot_type
FROM Payment p
JOIN Booking b
    ON p.booking_id = b.booking_id
JOIN Parking_Slot ps
    ON b.slot_id = ps.slot_id
JOIN Slot_Type st
    ON ps.slot_type_id = st.slot_type_id
GROUP BY st.slot_type_name;


##Revenue collected by payment method
SELECT
    pm.method_name,
    SUM(p.amount_paid) AS revenue_by_payment_method
FROM Payment p
JOIN Payment_Method pm
    ON p.payment_method_id = pm.payment_method_id
GROUP BY pm.method_name;


##List all successful payments with booking details
SELECT
    p.payment_id,
    b.booking_id,
    p.amount_paid,
    p.payment_time,
    p.payment_status
FROM Payment p
JOIN Booking b
    ON p.booking_id = b.booking_id
WHERE p.payment_status = 'SUCCESS';


##Calculate average parking duration per booking
SELECT
    b.booking_id,
    TIMESTAMPDIFF(MINUTE, e.entry_time, e.exit_time) AS parking_duration_minutes
FROM Booking b
JOIN Entry_Exit_Log e
    ON b.booking_id = e.booking_id;
    
##Find average parking duration by slot type
SELECT
    st.slot_type_name,
    AVG(TIMESTAMPDIFF(MINUTE, e.entry_time, e.exit_time)) AS avg_duration_minutes
FROM Entry_Exit_Log e
JOIN Booking b
    ON e.booking_id = b.booking_id
JOIN Parking_Slot ps
    ON b.slot_id = ps.slot_id
JOIN Slot_Type st
    ON ps.slot_type_id = st.slot_type_id
GROUP BY st.slot_type_name;

##Identify peak booking hours
SELECT
    HOUR(booking_start_time) AS booking_hour,
    COUNT(*) AS total_bookings
FROM Booking
GROUP BY booking_hour
ORDER BY total_bookings DESC;


##Slot utilization count (how many times each slot is used)
SELECT
    ps.slot_number,
    COUNT(b.booking_id) AS total_bookings
FROM Parking_Slot ps
LEFT JOIN Booking b
    ON ps.slot_id = b.slot_id
GROUP BY ps.slot_number;

##Detect potential overstay cases
SELECT
    b.booking_id,
    b.booking_end_time,
    e.exit_time,
    TIMESTAMPDIFF(MINUTE, b.booking_end_time, e.exit_time) AS overstay_minutes
FROM Booking b
JOIN Entry_Exit_Log e
    ON b.booking_id = e.booking_id
WHERE e.exit_time > b.booking_end_time;

##Total penalty revenue collected from violations
SELECT
    SUM(penalty_amount) AS total_penalty_revenue
FROM Violation;

##Penalty revenue grouped by violation type
SELECT
    violation_type,
    SUM(penalty_amount) AS penalty_revenue
FROM Violation
GROUP BY violation_type;


##Identify repeat violators (users with multiple violations)
SELECT
    u.full_name,
    COUNT(v.violation_id) AS total_violations
FROM Violation v
JOIN Booking b
    ON v.booking_id = b.booking_id
JOIN User u
    ON b.user_id = u.user_id
GROUP BY u.full_name
HAVING COUNT(v.violation_id) > 1;

##Total revenue generated by each user
SELECT
    u.full_name,
    SUM(p.amount_paid) AS total_revenue_generated
FROM Payment p
JOIN Booking b
    ON p.booking_id = b.booking_id
JOIN User u
    ON b.user_id = u.user_id
GROUP BY u.full_name;


##Compare EV slot demand vs regular slots
SELECT
    st.slot_type_name,
    COUNT(b.booking_id) AS total_bookings
FROM Booking b
JOIN Parking_Slot ps
    ON b.slot_id = ps.slot_id
JOIN Slot_Type st
    ON ps.slot_type_id = st.slot_type_id
GROUP BY st.slot_type_name;





